services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    container_name: data-crunch-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - data-crunch-network
  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: data-crunch-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
    networks:
      - data-crunch-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: data-crunch-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: data-crunch
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - data-crunch-network
  kafka-init:
    image: confluentinc/cp-kafka:7.7.7
    container_name: data-crunch-kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo 'Waiting for Kafka to be ready...'
      sleep 20
      echo 'Creating topics...'
      kafka-topics --create --if-not-exists --topic gps-pings --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1
      kafka-topics --create --if-not-exists --topic ride-requests --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1
      kafka-topics --create --if-not-exists --topic payments --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1
      kafka-topics --create --if-not-exists --topic driver-behavior --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1
      kafka-topics --create --if-not-exists --topic app-logs --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1
      kafka-topics --create --if-not-exists --topic dead-letter-queue --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1
      echo 'All topics created successfully!'
      "
    networks:
      - data-crunch-network

volumes:
  kafka_data:

networks:
  data-crunch-network:
    driver: bridge